CREATE DATABASE IF NOT EXISTS crowdfund_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE crowdfund_db;


CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE projects (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
title VARCHAR(255) NOT NULL,
short_desc VARCHAR(500),
description TEXT,
goal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
raised_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
image VARCHAR(255) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE contributions (
id INT AUTO_INCREMENT PRIMARY KEY,
project_id INT NOT NULL,
user_id INT NULL,
donor_name VARCHAR(255) DEFAULT NULL,
amount DECIMAL(12,2) NOT NULL,
currency VARCHAR(10) NOT NULL DEFAULT 'USD',
payment_provider VARCHAR(50) DEFAULT NULL,
provider_payment_id VARCHAR(255) DEFAULT NULL,
status VARCHAR(50) DEFAULT 'succeeded',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);


CREATE TABLE project_updates (
id INT AUTO_INCREMENT PRIMARY KEY,
project_id INT NOT NULL,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);